# Training data checks

In [84]:
from pathlib import Path
import pandas as pd

data_path = Path("..") / "data" / f"training_pop50.parquet"
df = pd.read_parquet(data_path)
print(f"Loaded {len(df):,} tracks from {data_path}")

Loaded 186,960 tracks from ../data/training_pop50.parquet

## Leading artist

Since we are collapsing multiple tracks artists into one, we checks the logic is behaving as expected: the leading artist is the only artist for all tracks in an album.

In [111]:
def consistent_first_artist(album_title: str, album_artist: str) -> bool:
    album_df = df[(df["album_name"] == album_title) & (df["artist_name"] == album_artist)]
    return set(df[df["id_upc"].isin(album_df["id_upc"])]["artist_name"]) == {album_artist}


ALBUMS_ARTISTS = [
    ("A Girl Like Me", "Rihanna"),
    ("Watch The Throne", "JAY-Z"),
    ("EVERYTHING IS LOVE", "The Carters"),
    ("An Evening With Silk Sonic", "Bruno Mars"),
    ("ASTROWORLD", "Travis Scott"),
    ("The Life Of Pablo", "Kanye West"),
    ("SOS", "SZA"),
    ("Random Access Memories", "Daft Punk"),
    ("Views", "Drake"),
    ("Humanz (Deluxe)", "Gorillaz"),
]

all([consistent_first_artist(t, a) for t, a in ALBUMS_ARTISTS])

True

In [108]:
df[df["album_name"] == "Humanz (Deluxe)"]

,track_rowid,track_name,artist_name,artist_rowid,album_rowid,album_name,album_type,label,release_date,release_date_precision,...,valence,explicit,track_popularity,artist_popularity,artist_followers,album_popularity,duration_ms,track_number,disc_number,total_tracks
5492,7008647,Momentz (feat. De La Soul),Gorillaz,4219215,546444,Humanz (Deluxe),album,Parlophone UK,2017-04-28,day,...,0.4870,1,51,82,13064787,68,196906,5,1,26
81066,7008653,Busted and Blue,Gorillaz,4219215,546444,Humanz (Deluxe),album,Parlophone UK,2017-04-28,day,...,0.0661,0,55,82,13064787,68,277053,11,1,26
106658,7008645,Strobelite (feat. Peven Everett),Gorillaz,4219215,546444,Humanz (Deluxe),album,Parlophone UK,2017-04-28,day,...,0.4970,0,57,82,13064787,68,272666,3,1,26
126457,7008644,Ascension (feat. Vince Staples),Gorillaz,4219215,546444,Humanz (Deluxe),album,Parlophone UK,2017-04-28,day,...,0.5190,1,59,82,13064787,68,155973,2,1,26
148100,7008646,Saturnz Barz (feat. Popcaan),Gorillaz,4219215,546444,Humanz (Deluxe),album,Parlophone UK,2017-04-28,day,...,0.2130,0,62,82,13064787,68,181906,4,1,26
158454,7008652,Andromeda (feat. DRAM),Gorillaz,4219215,546444,Humanz (Deluxe),album,Parlophone UK,2017-04-28,day,...,0.2570,0,64,82,13064787,68,197546,10,1,26
184285,7008659,She's My Collar (feat. Kali Uchis),Gorillaz,4219215,546444,Humanz (Deluxe),album,Parlophone UK,2017-04-28,day,...,0.4620,0,77,82,13064787,68,209560,17,1,26

In [83]:
album_df

Empty DataFrame
Columns: [track_rowid, track_name, artist_name, artist_rowid, album_rowid, album_name, album_type, label, release_date, release_date_precision, id_isrc, id_upc, time_signature, tempo, key, mode, danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, explicit, track_popularity, artist_popularity, artist_followers, album_popularity, duration_ms, track_number, disc_number, total_tracks]
Index: []

[0 rows x 33 columns]